version: "3"
services:
  strapi:
    container_name: strapi
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
#      DATABASE_CLIENT: postgres
#      DATABASE_HOST: postgres
#      DATABASE_NAME: ${POSTGRES_DB}
#      DATABASE_USERNAME: ${POSTGRES_USER}
#      DATABASE_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      NODE_ENV: development
      PORT: ${PORT}
    volumes:
      - ./_docker_volumes/public/uploads:/opt/app/public/uploads
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
    ports:
      - "1338:1338"
#    depends_on:
#      - postgres
#
#  postgres:
#    container_name: postgres
#    platform: linux/amd64 #for platform error on Apple M1 chips
#    env_file: .env
#    image: postgres:14.5-alpine
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#      - ./_docker_volumes/postgres:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
